// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package book

import (
	"PRACTICESTUFF/example-go/domain"
	"context"
	"sync"
)

var (
	lockServiceMockAddTags           sync.RWMutex
	lockServiceMockCreate            sync.RWMutex
	lockServiceMockCreateBatch       sync.RWMutex
	lockServiceMockDelete            sync.RWMutex
	lockServiceMockFind              sync.RWMutex
	lockServiceMockFindAll           sync.RWMutex
	lockServiceMockIsCategoryExisted sync.RWMutex
	lockServiceMockUpdate            sync.RWMutex
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
//     func TestSomethingThatUsesService(t *testing.T) {
//
//         // make and configure a mocked Service
//         mockedService := &ServiceMock{
//             AddTagsFunc: func(ctx context.Context, p *domain.Book, t []domain.Tag) ([]domain.BookTag, error) {
// 	               panic("mock out the AddTags method")
//             },
//             CreateFunc: func(ctx context.Context, p *domain.Book) error {
// 	               panic("mock out the Create method")
//             },
//             CreateBatchFunc: func(ctx context.Context, p []domain.Book) ([]domain.Book, error) {
// 	               panic("mock out the CreateBatch method")
//             },
//             DeleteFunc: func(ctx context.Context, p *domain.Book) error {
// 	               panic("mock out the Delete method")
//             },
//             FindFunc: func(ctx context.Context, p *domain.Book) (*domain.Book, error) {
// 	               panic("mock out the Find method")
//             },
//             FindAllFunc: func(ctx context.Context, queries FindAllQueries) ([]domain.Book, error) {
// 	               panic("mock out the FindAll method")
//             },
//             IsCategoryExistedFunc: func(ctx context.Context, cat *domain.Category) (bool, error) {
// 	               panic("mock out the IsCategoryExisted method")
//             },
//             UpdateFunc: func(ctx context.Context, p *domain.Book) (*domain.Book, error) {
// 	               panic("mock out the Update method")
//             },
//         }
//
//         // use mockedService in code that requires Service
//         // and then make assertions.
//
//     }
type ServiceMock struct {
	// AddTagsFunc mocks the AddTags method.
	AddTagsFunc func(ctx context.Context, p *domain.Book, t []domain.Tag) ([]domain.BookTag, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, p *domain.Book) error

	// CreateBatchFunc mocks the CreateBatch method.
	CreateBatchFunc func(ctx context.Context, p []domain.Book) ([]domain.Book, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, p *domain.Book) error

	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, p *domain.Book) (*domain.Book, error)

	// FindAllFunc mocks the FindAll method.
	FindAllFunc func(ctx context.Context, queries FindAllQueries) ([]domain.Book, error)

	// IsCategoryExistedFunc mocks the IsCategoryExisted method.
	IsCategoryExistedFunc func(ctx context.Context, cat *domain.Category) (bool, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, p *domain.Book) (*domain.Book, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddTags holds details about calls to the AddTags method.
		AddTags []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P *domain.Book
			// T is the t argument value.
			T []domain.Tag
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P *domain.Book
		}
		// CreateBatch holds details about calls to the CreateBatch method.
		CreateBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P []domain.Book
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P *domain.Book
		}
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P *domain.Book
		}
		// FindAll holds details about calls to the FindAll method.
		FindAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Queries is the queries argument value.
			Queries FindAllQueries
		}
		// IsCategoryExisted holds details about calls to the IsCategoryExisted method.
		IsCategoryExisted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cat is the cat argument value.
			Cat *domain.Category
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P *domain.Book
		}
	}
}

// AddTags calls AddTagsFunc.
func (mock *ServiceMock) AddTags(ctx context.Context, p *domain.Book, t []domain.Tag) ([]domain.BookTag, error) {
	if mock.AddTagsFunc == nil {
		panic("ServiceMock.AddTagsFunc: method is nil but Service.AddTags was just called")
	}
	callInfo := struct {
		Ctx context.Context
		P   *domain.Book
		T   []domain.Tag
	}{
		Ctx: ctx,
		P:   p,
		T:   t,
	}
	lockServiceMockAddTags.Lock()
	mock.calls.AddTags = append(mock.calls.AddTags, callInfo)
	lockServiceMockAddTags.Unlock()
	return mock.AddTagsFunc(ctx, p, t)
}

// AddTagsCalls gets all the calls that were made to AddTags.
// Check the length with:
//     len(mockedService.AddTagsCalls())
func (mock *ServiceMock) AddTagsCalls() []struct {
	Ctx context.Context
	P   *domain.Book
	T   []domain.Tag
} {
	var calls []struct {
		Ctx context.Context
		P   *domain.Book
		T   []domain.Tag
	}
	lockServiceMockAddTags.RLock()
	calls = mock.calls.AddTags
	lockServiceMockAddTags.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *ServiceMock) Create(ctx context.Context, p *domain.Book) error {
	if mock.CreateFunc == nil {
		panic("ServiceMock.CreateFunc: method is nil but Service.Create was just called")
	}
	callInfo := struct {
		Ctx context.Context
		P   *domain.Book
	}{
		Ctx: ctx,
		P:   p,
	}
	lockServiceMockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockServiceMockCreate.Unlock()
	return mock.CreateFunc(ctx, p)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedService.CreateCalls())
func (mock *ServiceMock) CreateCalls() []struct {
	Ctx context.Context
	P   *domain.Book
} {
	var calls []struct {
		Ctx context.Context
		P   *domain.Book
	}
	lockServiceMockCreate.RLock()
	calls = mock.calls.Create
	lockServiceMockCreate.RUnlock()
	return calls
}

// CreateBatch calls CreateBatchFunc.
func (mock *ServiceMock) CreateBatch(ctx context.Context, p []domain.Book) ([]domain.Book, error) {
	if mock.CreateBatchFunc == nil {
		panic("ServiceMock.CreateBatchFunc: method is nil but Service.CreateBatch was just called")
	}
	callInfo := struct {
		Ctx context.Context
		P   []domain.Book
	}{
		Ctx: ctx,
		P:   p,
	}
	lockServiceMockCreateBatch.Lock()
	mock.calls.CreateBatch = append(mock.calls.CreateBatch, callInfo)
	lockServiceMockCreateBatch.Unlock()
	return mock.CreateBatchFunc(ctx, p)
}

// CreateBatchCalls gets all the calls that were made to CreateBatch.
// Check the length with:
//     len(mockedService.CreateBatchCalls())
func (mock *ServiceMock) CreateBatchCalls() []struct {
	Ctx context.Context
	P   []domain.Book
} {
	var calls []struct {
		Ctx context.Context
		P   []domain.Book
	}
	lockServiceMockCreateBatch.RLock()
	calls = mock.calls.CreateBatch
	lockServiceMockCreateBatch.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ServiceMock) Delete(ctx context.Context, p *domain.Book) error {
	if mock.DeleteFunc == nil {
		panic("ServiceMock.DeleteFunc: method is nil but Service.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		P   *domain.Book
	}{
		Ctx: ctx,
		P:   p,
	}
	lockServiceMockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	lockServiceMockDelete.Unlock()
	return mock.DeleteFunc(ctx, p)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedService.DeleteCalls())
func (mock *ServiceMock) DeleteCalls() []struct {
	Ctx context.Context
	P   *domain.Book
} {
	var calls []struct {
		Ctx context.Context
		P   *domain.Book
	}
	lockServiceMockDelete.RLock()
	calls = mock.calls.Delete
	lockServiceMockDelete.RUnlock()
	return calls
}

// Find calls FindFunc.
func (mock *ServiceMock) Find(ctx context.Context, p *domain.Book) (*domain.Book, error) {
	if mock.FindFunc == nil {
		panic("ServiceMock.FindFunc: method is nil but Service.Find was just called")
	}
	callInfo := struct {
		Ctx context.Context
		P   *domain.Book
	}{
		Ctx: ctx,
		P:   p,
	}
	lockServiceMockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	lockServiceMockFind.Unlock()
	return mock.FindFunc(ctx, p)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//     len(mockedService.FindCalls())
func (mock *ServiceMock) FindCalls() []struct {
	Ctx context.Context
	P   *domain.Book
} {
	var calls []struct {
		Ctx context.Context
		P   *domain.Book
	}
	lockServiceMockFind.RLock()
	calls = mock.calls.Find
	lockServiceMockFind.RUnlock()
	return calls
}

// FindAll calls FindAllFunc.
func (mock *ServiceMock) FindAll(ctx context.Context, queries FindAllQueries) ([]domain.Book, error) {
	if mock.FindAllFunc == nil {
		panic("ServiceMock.FindAllFunc: method is nil but Service.FindAll was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Queries FindAllQueries
	}{
		Ctx:     ctx,
		Queries: queries,
	}
	lockServiceMockFindAll.Lock()
	mock.calls.FindAll = append(mock.calls.FindAll, callInfo)
	lockServiceMockFindAll.Unlock()
	return mock.FindAllFunc(ctx, queries)
}

// FindAllCalls gets all the calls that were made to FindAll.
// Check the length with:
//     len(mockedService.FindAllCalls())
func (mock *ServiceMock) FindAllCalls() []struct {
	Ctx     context.Context
	Queries FindAllQueries
} {
	var calls []struct {
		Ctx     context.Context
		Queries FindAllQueries
	}
	lockServiceMockFindAll.RLock()
	calls = mock.calls.FindAll
	lockServiceMockFindAll.RUnlock()
	return calls
}

// IsCategoryExisted calls IsCategoryExistedFunc.
func (mock *ServiceMock) IsCategoryExisted(ctx context.Context, cat *domain.Category) (bool, error) {
	if mock.IsCategoryExistedFunc == nil {
		panic("ServiceMock.IsCategoryExistedFunc: method is nil but Service.IsCategoryExisted was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cat *domain.Category
	}{
		Ctx: ctx,
		Cat: cat,
	}
	lockServiceMockIsCategoryExisted.Lock()
	mock.calls.IsCategoryExisted = append(mock.calls.IsCategoryExisted, callInfo)
	lockServiceMockIsCategoryExisted.Unlock()
	return mock.IsCategoryExistedFunc(ctx, cat)
}

// IsCategoryExistedCalls gets all the calls that were made to IsCategoryExisted.
// Check the length with:
//     len(mockedService.IsCategoryExistedCalls())
func (mock *ServiceMock) IsCategoryExistedCalls() []struct {
	Ctx context.Context
	Cat *domain.Category
} {
	var calls []struct {
		Ctx context.Context
		Cat *domain.Category
	}
	lockServiceMockIsCategoryExisted.RLock()
	calls = mock.calls.IsCategoryExisted
	lockServiceMockIsCategoryExisted.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ServiceMock) Update(ctx context.Context, p *domain.Book) (*domain.Book, error) {
	if mock.UpdateFunc == nil {
		panic("ServiceMock.UpdateFunc: method is nil but Service.Update was just called")
	}
	callInfo := struct {
		Ctx context.Context
		P   *domain.Book
	}{
		Ctx: ctx,
		P:   p,
	}
	lockServiceMockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	lockServiceMockUpdate.Unlock()
	return mock.UpdateFunc(ctx, p)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedService.UpdateCalls())
func (mock *ServiceMock) UpdateCalls() []struct {
	Ctx context.Context
	P   *domain.Book
} {
	var calls []struct {
		Ctx context.Context
		P   *domain.Book
	}
	lockServiceMockUpdate.RLock()
	calls = mock.calls.Update
	lockServiceMockUpdate.RUnlock()
	return calls
}
